- name: Garantindo repositório
  yum_repository:
    name: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    description: Docker CE Stable
    file: docker-ce