---
- name: Garantindo pré-dependências
  package:
    name: ['apt-transport-https', 'ca-certificates', 'gnupg-agent', 'software-properties-common']
    state: present
- name: Garantindo chave do repositório
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: Garantindo repositório
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker-ce
...