---

- hosts: all
  become: yes
  tasks:
    - name: Garantindo configuração do /etc/hosts
      #lineinfile checa o arquivo e adiciona as linhas inexistentes
      lineinfile: 
        path: /etc/hosts
        line: '{{ item }}'
      #CHUMBA OS NODES NO /etc/hosts
      loop: 
      - '172.27.11.10 automation'
      - '172.27.11.20 balancer'
      - '172.27.11.30 database'
      - '172.27.11.100 docker1'
      - '172.27.11.200 docker2'

...